mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('post_list', views.PostListView.as_view(), name='post_list'),
	path('post_create', views.PostCreateView.as_view(), name='post_create'),
	path('post_detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'), 
	path('post_update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'), 
	path('post_delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'), 
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	title = models.CharField('タイトル', max_length=200)
	text = models.TextField('本文')
	date = models.DateTimeField('日付', default=timezone.now)
	
	def __str__(self): # Postモデルが直接呼び出された時に返す値
		return self.title # 記事タイトルを返す

mysite/blog/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
	# DjangoのModelFormでは強力なValidationを使える
	class Meta:
		model = Post # Post モデルと接続し、Postモデルの内容に応じてformを作ってくれる
		fields = ('title', 'text')  #　入力するカラムを指定
		# fields = 'all'と定義して全てのカラムを手入力するように指定も可能

mysite/blog/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import PostCreateForm # forms.py で作ったクラスをimport
from .models import Post

# Create your views here.

# class IndexView(generic.TemplateView):
# 	template_name = 'blog/index.html'

class PostListView(generic.ListView):
	model = Post

class PostCreateView(generic.CreateView):
	model = Post # 作成したい modelを指定
	form_class = PostCreateForm # 作成した form　クラスを指定
	success_url = reverse_lazy('blog:post_list')  # 記事作成に成功した時のリダイレクト先を指定
	
class PostDetailView(generic.DetailView):
	model = Post  #pk(primary key)はurls.pyで指定しているのでここではmodelを呼び出すだけで済む

class PostUpdateView(generic.UpdateView):
	model = Post
	form_class = PostCreateForm  # PostCreateFormをほぼそのまま活用できる
	success_url = reverse_lazy('blog:post_detail')

class PostDeleteView(generic.DeleteView):
	model = Post
	success_url = reverse_lazy('blog:post_list')

mysite/templates/base.html
<!doctype html>
<html lang="ja">

<head>
	<title>Taton's Blog</title>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
		integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>

	<div class="container">

		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="{% url 'blog:post_list' %}">トップ</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'blog:post_create' %}">投稿</a>
					</li>
				</ul>
			</div>
		</nav>

		<!-- このblockの中で各templateの記載内容が呼び出される -->
		{% block content %}
		{% endblock %}

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
		integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
		crossorigin="anonymous"></script>

</body>

</html>

mysite/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
	<table>
		<tr>
			<th>タイトル</th>
			<td>{{ post.title }}</td>
		</tr>
		<tr>
			<th>本文</th>
			<td>{{ post.text }}</td>
		</tr>
		<tr>
			<th>日付</th>
			<td>{{ post.date }}</td>
		</tr>
	</table>
	<p>こちらのデータを削除します。</p>
	<button type="submit">送信</button>
	{% csrf_token %}<!-- CSRF対策 -->
</form>
{% endblock %}

mysite/templates/blog/post_detail.html
{% extends 'base.html' %} 
{% block content %}
<table>
	<tr>
		<th>タイトル</th>
		<td>{{ post.title }}</td>
	</tr>
	<tr>
		<th>本文</th>
		<!-- linebreaksbr を入れると改行タグでちゃんと改行して表示されるようになる -->
		<td>{{ post.text | linebreaksbr}}</td>
	</tr>
	<tr>
		<th>日付</th>
		<td>{{ post.date }}</td>
	</tr>
</table>
{% endblock %}

mysite/templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}
<p>{{ post.title }}</p>
<!-- actionにはサーバのどのURLに対して情報を送信する
actionを空欄にすると現在開いている URL = /blog/post_create に値を返す
views.py の PostCreateView が再度呼び出されることになる -->
<form action="" method="POST">
	<table class="table">
		<tr>
			<th>タイトル</th>
			<td>{{ form.title }}</td>
		</tr>
		<tr>
			<th>本文</th>
			<td>{{ form.text }}</td>
		</tr>
	</table>
	<button type="submit" class="btn btn-primary">送信</button>
	{% csrf_token %}
</form>
{% endblock %}

mysite/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}

<table class="table">
	<thead>
		<tr>
			<th>タイトル</th>
			<th>日付</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for post in post_list %}
		<tr>
			<!-- 【重要】「url 'アプリ名:逆引きURL'　渡されるモデル.pk」という描き方 -->
			<td><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></td>
			<td>{{ post.date }}</td>
			<td>
				<!-- superuserでログインしている時にのみ表示 -->
				{% if user.is_superuser %}
				<!-- HTMLを　アプリ名_モデル名_change にすると　admin でそのまま編集 -->
					<a href="{% url 'blog:post_update' post.pk %}">編集</a>
				{% endif %}
			</td>
			<td>
				{% if user.is_superuser %}
					<a href="{% url 'blog:post_delete' post.pk %}">削除</a>
					{% endif %}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}